language: python
python:
  - "3.5"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install virtual enviroment 
  - conda create -q -n qmworks python=3.5
  - conda install -c anaconda hdf5
  - conda install -y -q -c https://conda.anaconda.org/rdkit rdkit
  - source activate qmworks

  - pip install cython h5py
  - pip install -e git://github.com/SCM-NV/plams.git@master#egg=Plams
  - pip install -e git://github.com/NLeSC/noodles.git@devel#egg=Noodles
  - pip install -e git://github.com/SCM-NV/qmworks.git@master#egg=qmworks
  - pip install -U .
  - pip install -U ".[test]"
  
script: nosetests --with-coverage --cover-erase --cover-package=nac --cover-xml