sudo: required
language: none
install:
  - export CXX="g++-7"
  - export CC="gcc-7"


addons:
  apt:
    packages: g++-7
    sources:
      - ubuntu-toolchain-r-test

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  # Useful for debugging any issues with conda
  - conda info -a

  # Install virtual enviroment
  - conda create --name namd python=3.6
  - source activate namd
  - conda install -c conda-forge cython eigen h5py highfive libint pybind11 rdkit

  - pip install "git+https://github.com/SCM-NV/PLAMS@master#egg=plams-1.2"
  - pip install "https://github.com/SCM-NV/qmflows/tarball/master#egg=qmflows"
  - pip install .[test]
  

before_script:
  - conda list

script:
  - py.test -m "not (slow or long)" --cov=nac test
  - coverage xml && coverage report -m

after_success:
  - python-codacy-coverage -r coverage.xml

branches:
  only:
   - master
