sudo: required
language: generic
dist: bionic

matrix:
  include:
    - os: linux
      env:
        - PYTHON_VERSION=3.6
    - os: linux
      env:
        - PYTHON_VERSION=3.7
    - os: linux
      env:
        - PYTHON_VERSION=3.8
    - os: osx
      env:
        - MCONDA_PYTHON_MAJOR=3
        - MCONDA_PYTHON_VERSION=3.8

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "f.zapata@esciencecenter.nl"
    - MCONDA_LINUX="Linux-x86_64"
    - MCONDA_OSX="MacOSX-x86_64"

before_install:
  - |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get -y install cp2k

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export MCONDA_OS=$MCONDA_LINUX
      export CC=gcc-7
      export CXX=g++-7
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export MCONDA_OS=$MCONDA_OSX
    fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${MCONDA_OS}.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  # Useful for debugging any issues with conda
  - conda info -a

  # Install python env
  - conda create --name namd python=${PYTHON_VERSION}
  - source activate namd
  - conda install -c conda-forge/label/gcc7 highfive h5py eigen cython rdkit pybind11
  - conda install -c conda-forge libint==2.4.2
  - pip install .[test] -v
  

before_script:
  - conda list

script:
  - pytest --cov=nac test

after_success:
  - python-codacy-coverage -r coverage.xml

branches:
  only:
   - master
