[build-system]
# Minimum requirements for the build system to execute.
requires = ['Cython', 'setuptools>=48.0', 'wheel', 'pybind11>=2.2.4']

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "scm.plams.*",
    "h5py.*",
    "scipy.*",
    "noodles.*",
    "schema.*",
    "mendeleev.*",
    "pybind11.*",
    "Cython.*",
]
ignore_missing_imports = true

[tool.cibuildwheel]
build-verbosity = "3"
before-build = "echo 1"
repair-wheel-command = "auditwheel -v repair -w {dest_dir} {wheel}"
manylinux-x86_64-image = "manylinux2014"
environment = { QMFLOWS_INCLUDEDIR="include", QMFLOWS_LIBDIR="lib" }
