name: build with conda

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [3.8, 3.9]


    steps:
    - uses: actions/checkout@v2
    - name: Install cp2k
      run: sudo apt install cp2k cp2k-data
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda
    - run: conda --version
    - run: python --version
    - run: |
        conda install -c conda-forge libint==2.6.0 highfive h5py eigen cython rdkit pybind11

    - name: Install the package
      run: pip install -e .[test]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pytest -m "not (slow or long)"

    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella