name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_wheels:
    name: Build wheels ${{ matrix.version }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
        - [ubuntu-20.04, manylinux_x86_64]
        version:
        - "cp37"
        - "cp38"
        - "cp39"
        - "cp310"

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: ${{ matrix.version }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build wheels sdist
    runs-on: ubuntu-latest
    env:
      QMFLOWS_INCLUDEDIR: ""
      QMFLOWS_LIBDIR: ""
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install Cython "setuptools>=48.0" wheel "pybind11>=2.2.4"

      - name: Python info
        run: |
          which python
          python --version

      - name: Installed packages
        run: pip list

      - name: Build sdist
        run: |
          python setup.py sdist
          tree dist

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*.tar.gz

  upload_wheels:
    name: Upload wheels
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install twine

      - name: Python info
        run: |
          which python
          python --version

      - name: Installed packages
        run: pip list

      - name: Validate wheels
        run: |
          tree dist
          twine check dist/*

      - name: Publish wheels
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
