name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Build wheels (${{ matrix.os }}; py ${{ matrix.version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: false

      - name: Install dependencies
        run: |
          conda create -n test -c conda-forge python=${{ matrix.version }} boost eigen libint==2.6.0 highfive
          source $CONDA/bin/activate test
          pip install Cython setuptools wheel pybind11>=2.2.4

      - name: Conda info
        run: |
          source $CONDA/bin/activate test
          conda info

      - name: Conda list
        run: conda list -n test

      - name: Build wheels
        run: |
          source $CONDA/bin/activate test
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]] && [[ "${{ matrix.version }}" == "3.10" ]]; then
            python setup.py sdist bdist_wheel
          else
            python setup.py bdist_wheel
          fi

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: dist

  publish:
    name: Publish wheels
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Download wheels
        uses: actions/download-artifact@v2

      - name: Show wheels
        run: ls -l artifact/

      - name: Publish wheels
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: artifact/
