name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: false

      - name: Install dependencies
        run: conda create -n test -c conda-forge boost eigen libint==2.6.0 highfive Cython setuptools wheel "pybind11>=2.2.4"

      - name: Conda info
        run: |
          source $CONDA/bin/activate test
          conda info

      - name: Conda list
        run: conda list -n test

      - name: Build wheels
        run: |
          source $CONDA/bin/activate test
          python setup.py sdist

      - name: Publish wheels
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
