name: build with conda

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        version: [3.7, 3.8]
        os: [macos-latest, ubuntu-latest]


    steps:
    - uses: actions/checkout@master
    - name: Install cp2k
      run: sudo apt install cp2k
    - name: Setup conda
      uses: s-weigand/setup-conda@master
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda
    - run: conda --version
    - run: python --version
    - run: |
        conda install -c conda-forge libint==2.6.0 highfive h5py eigen cython rdkit pybind11

    - name: Install the package
      run: pip install -e .[test]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pip install pytest pytest-cov
        pytest test

    - name: coverage
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella