name: build with conda

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['3.8', '3.9']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Install cp2k
      run: sudo apt install cp2k cp2k-data

    - name: Info CP2K
      run: cp2k.popt --version

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: anaconda, conda-forge

    - name: Install dependencies
      run: |
        conda create -n test -c conda-forge python=${{ matrix.version }} boost eigen libint==2.6.0 highfive
        source $CONDA/bin/activate test
        pip install -r ./test_requirements.txt

    - name: Install the package
      run: |
        source $CONDA/bin/activate test
        pip install -e . -vvv

    - name: Conda info
      run: |
        source $CONDA/bin/activate test
        conda info

    - name: Conda list
      run: conda list -n test

    - name: Test with pytest
      run: |
        source $CONDA/bin/activate test
        pytest -m "not (slow or long)"

    - name: coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        name: codecov-umbrella
